# Generated by Django 5.0.3 on 2024-03-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinFlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('H', 'Head'), ('T', 'Tale')], max_length=1)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
